local dmodel = {}

dmodel.Decorations = {
  [1] = 'Attack Jewel',
  [2] = 'Challenger Jewel',
  [3] = 'Flawless Jewel',
  [4] = 'Furor Jewel',
  [5] = 'Crisis Jewel',
  [6] = 'Expert Jewel',
  [7] = 'Critical Jewel',
  [8] = 'Tenderizer Jewel',
  [9] = 'Throttle Jewel',
  [10] = 'Mighty Jewel',
  [11] = 'Crit Element Jewel',
  [12] = 'Mastery Jewel',
  [13] = 'Blaze Jewel',
  [14] = 'Stream Jewel',
  [15] = 'Frost Jewel',
  [16] = 'Bolt Jewel',
  [17] = 'Dragon Jewel',
  [18] = 'Venom Jewel',
  [19] = 'Paralyzer Jewel',
  [20] = 'Sleep Jewel',
  [21] = 'Blast Jewel',
  [22] = 'Handicraft Jewel',
  [23] = 'Razor Jewel',
  [24] = 'Thrift Jewel',
  [25] = 'Sharp Jewel',
  [26] = "Mind's Eye Jewel",
  [27] = 'Precise Jewel',
  [28] = 'Blunt Jewel',
  [29] = 'Unlucky',
  [30] = 'Charger Jewel',
  [31] = 'Enhancer Jewel',
  [32] = 'Sprinter Jewel',
  [33] = 'Physique Jewel',
  [34] = 'Refresh Jewel',
  [35] = 'Ironwall Jewel',
  [36] = 'Shield Jewel',
  [37] = 'Guardian Jewel',
  [38] = 'Draw Jewel',
  [39] = 'Gambit Jewel',
  [40] = 'Sheath Jewel',
  [41] = 'KO Jewel',
  [42] = 'Drain Jewel',
  [43] = 'Slider Jewel',
  [44] = 'Sonorous Jewel',
  [45] = 'Artillery Jewel',
  [46] = 'Magazine Jewel',
  [47] = 'Trueshot Jewel',
  [48] = 'Forceshot Jewel',
  [49] = 'Pierce Jewel',
  [50] = 'Spread Jewel',
  [51] = 'Capacity Jewel',
  [52] = 'Quickload Jewel',
  [53] = 'Absorber Jewel',
  [54] = 'Sniper Jewel',
  [55] = 'Salvo Jewel',
  [56] = 'Defense Jewel',
  [57] = 'Protection Jewel',
  [58] = 'Medicine Jewel',
  [59] = 'Recovery Jewel',
  [60] = 'Gobbler Jewel',
  [61] = 'Earplug Jewel',
  [62] = 'Wind Res Jewel',
  [63] = 'Footing Jewel',
  [64] = 'Bubble Jewel',
  [65] = 'Evasion Jewel',
  [66] = 'Jumping Jewel',
  [67] = 'Fire Res Jewel',
  [68] = 'Water Res Jewel',
  [69] = 'Ice Res Jewel',
  [70] = 'Thunder Res Jewel',
  [71] = 'Dragon Res Jewel',
  [72] = 'Resistor Jewel',
  [73] = 'Antidote Jewel',
  [74] = 'Antipara Jewel',
  [75] = 'Pep Jewel',
  [76] = 'Steadfast Jewel',
  [77] = 'Muck Jewel',
  [78] = 'Antiblast Jewel',
  [79] = 'Botany Jewel',
  [80] = 'Geology Jewel',
  [81] = 'Destroyer Jewel',
  [82] = 'Unlucky',
  [83] = 'Unlucky',
  [84] = 'Fate Jewel',
  [85] = 'Grinder Jewel',
  [86] = 'Bomber Jewel',
  [87] = 'Fungiform Jewel',
  [88] = 'Enduring Jewel',
  [89] = 'Friendship Jewel',
  [90] = 'Satiated Jewel',
  [91] = 'Potential Jewel',
  [92] = 'Fortitude Jewel',
  [93] = 'Brace Jewel',
  [94] = 'Leap Jewel',
  [95] = 'Carver Jewel',
  [96] = 'Hungerless Jewel',
  [97] = 'Dive Jewel',
  [98] = 'Diversion Jewel',
  [99] = 'Rodeo Jewel',
  [100] = 'Unlucky',
  [101] = 'Unlucky',
  [102] = 'Unlucky',
  [103] = 'Unlucky',
  [104] = 'Wirebug Jewel',
  [105] = 'Wall Run Jewel',
  [106] = 'Counter Jewel',
  [107] = 'Quickswitch Jewel',
  [108] = 'Hellfire Jewel',
  [109] = 'Unlucky',
  [110] = 'Hard Fire Res Jewel',
  [111] = 'Hard Water Res Jewel',
  [112] = 'Hard Ice Res Jewel',
  [113] = 'Hard Thunder Res Jewel',
  [114] = 'Hard Dragon Res Jewel',
  [115] = 'Hard Antidote Jewel',
  [116] = 'Hard Antipara Jewel',
  [117] = 'Hard Pep Jewel',
  [118] = 'Hard Antiblast Jewel',
  [119] = 'Hard Botany Jewel',
  [120] = 'Hard Geology Jewel',
  [121] = 'Hard Satiated Jewel',
  [122] = 'Hard Drain Jewel',
  [123] = 'Hard Enduring Jewel',
  [124] = 'Hard Hungerless Jewel',
  [125] = 'Blaze Jewel+',
  [126] = 'Hard Blaze Jewel',
  [127] = 'Hard Blaze Jewel+',
  [128] = 'Stream Jewel+',
  [129] = 'Hard Stream Jewel',
  [130] = 'Hard Stream Jewel+',
  [131] = 'Frost Jewel+',
  [132] = 'Hard Frost Jewel',
  [133] = 'Hard Frost Jewel+',
  [134] = 'Bolt Jewel+',
  [135] = 'Hard Bolt Jewel',
  [136] = 'Hard Bolt Jewel+',
  [137] = 'Dragon Jewel+',
  [138] = 'Hard Dragon Jewel',
  [139] = 'Hard Dragin Jewel+',
  [140] = 'Defense Jewel+',
  [141] = 'Hard Defense Jewel',
  [142] = 'Hard Defense Jewel++',
  [143] = 'Hard Bomber Jewel',
  [144] = 'Hard Grinder Jewel',
  [145] = 'Medicine Jewel+',
  [146] = 'Physique Jewel+',
  [147] = 'Wirebug Jewel+',
  [148] = 'Hard Wall Run Jewel',
  [149] = 'Hard Venom Jewel',
  [150] = 'Hard Recovery Jewel',
  [151] = 'Protection Jewel+',
  [152] = 'Gobbler Jewel+',
  [153] = 'Resistor Jewel+',
  [154] = 'Destryoer Jewel+',
  [155] = 'Hard Friendship Jewel',
  [156] = 'Hard Friendship Jewel+',
  [157] = 'Evasion Jewel+',
  [158] = 'Sheath Jewel+',
  [159] = 'Hard Sniper Jewel',
  [160] = 'Gambit Jewel+',
  [161] = 'Hard Brace Jewel',
  [162] = 'Bubble Jewel+',
  [163] = 'KO Jewel+',
  [164] = 'Jumping Jewel+',
  [165] = 'Hard Wind Res Jewel',
  [166] = 'Counter Jewel+',
  [167] = 'Unlucky',
  [168] = 'Unlucky',
  [169] = 'Refresh Jewel+',
  [170] = 'Ironwall Jewel+',
  [171] = 'Shield Jewel+',
  [172] = 'Precise Jewel+',
  [173] = 'Mighty Jewel+',
  [174] = 'Crit Element Jewel+',
  [175] = 'Charger Jewel+',
  [176] = 'Sprinter Jewel+',
  [177] = 'Guardian Jewel+',
  [178] = 'Unlucky',
  [179] = 'Draw Jewel+',
  [180] = 'Fungiform Jewel+',
  [181] = 'Hard Steadfast Jewel',
  [182] = 'Potential Jewel+',
  [183] = 'Razor Jewel+',
  [184] = 'Unlucky',
  [185] = "Mind's Eye Jewel+",
  [186] = 'Quickswitch Jewel+',
  [187] = 'Artillery Jewel+',
  [188] = 'Earplug Jewel+',
  [189] = 'Enhancer Jewel+',
  [190] = 'Trueshot Jewel+',
  [191] = 'Magazine Jewel+',
  [192] = 'Footing Jewel+',
  [193] = 'Blast Jewel+',
  [194] = 'Spread Jewel+',
  [195] = 'Unlucky',
  [196] = 'Furor Jewel+',
  [197] = 'Furor Jewel+',
  [198] = 'Throttle Jewel+',
  [199] = 'Paralyzer Jewel+',
  [200] = 'Sleep Jewel+',
  [201] = 'Sharp Jewel+',
  [202] = 'Forceshot Jewel+',
  [203] = 'Pierce Jewel+',
  [204] = 'Unlucky',
  [205] = 'Hellfire Jewel+',
  [206] = 'Handicraft Jewel+',
  [207] = 'Fate Jewel+',
  [208] = 'Mastery Jewel+',
  [209] = 'Flawless Jewel+',
  [210] = 'Foil Jewel',
  [211] = 'Polisher Pro Jewel',
  [212] = 'SpiritBird´s Call jewel',
  [213] = 'Charge Jewel',
  [214] = 'Phoenix Jewel',
  [215] = 'Bladescale Jewel',
  [216] = 'Flywall Jewel',
  [217] = 'Chain Jewel',
  [218] = 'Redirection Jewel',
  [219] = 'Foray Jewel',
  [220] = 'Unlucky',
  [221] = 'Breath Jewel',
  [222] = 'Unlucky',
  [223] = 'Mighty Bow Jewel',
  [224] = 'Sniper Jewel+',
  [225] = 'Cornerstone Jewel',
  [226] = 'Elemental Exploit Jewel',
  [227] = 'Counter Attack Jewel',
  [228] = 'Backstab Jewel',
  [229] = 'Unlucky',
  [230] = 'Trigger Jewel',
  [231] = 'Embolden Jewel',
  [232] = 'Intrepid Jewel',
  [233] = 'Unlucky',
  [234] = 'Unlucky',
  [235] = 'Unlucky',
  [236] = 'Unlucky',
  [237] = 'Unlucky',
  [238] = 'Phoenix Jewel+',
  [239] = 'Haze Jewel',
  [240] = 'Charge Jewel+',
  [241] = 'Foil Jewel+ ',
  [242] = 'Bloodening Jewel',
  [243] = 'Polisher Pro Jewel+',
  [244] = 'Ironshell Jewel',
  [245] = 'Flamescale Jewel',
  [246] = 'Rediraction Jewel+',
  [247] = 'Dragon Spirit Jewel',
  [248] = 'Element Exploit Jewel+',
  [249] = 'Hard Cornerstone Jewel',
  [250] = 'Counter Attack Jewel+',
  [251] = 'Backstab Jewel+',
  [252] = 'Foray Jewel+',
  [253] = 'Chain Jewel+',
  [254] = 'Bloddlust Jewel',
  [255] = 'Eembolden Jewel+',
  [256] = 'Intrepid Jewel+',
  [257] = 'Trigger Jewel+',
  [258] = 'Unlucky',
  [259] = 'Shockproof Jewel',
  [260] = 'Unlucky',
  [261] = 'Bladescale Jewel+',
}

---@type UnluckyDecorations
dmodel.UnluckyDecorations = {
  [29] = 'Unlucky',
  [82] = 'Unlucky',
  [83] = 'Unlucky',
  [100] = 'Unlucky',
  [101] = 'Unlucky',
  [102] = 'Unlucky',
  [103] = 'Unlucky',
  [109] = 'Unlucky',
  [167] = 'Unlucky',
  [168] = 'Unlucky',
  [178] = 'Unlucky',
  [184] = 'Unlucky',
  [195] = 'Unlucky',
  [204] = 'Unlucky',
  [220] = 'Unlucky',
  [222] = 'Unlucky',
  [229] = 'Unlucky',
  [233] = 'Unlucky',
  [234] = 'Unlucky',
  [235] = 'Unlucky',
  [236] = 'Unlucky',
  [237] = 'Unlucky',
  [258] = 'Unlucky',
  [260] = 'Unlucky',
}

dmodel.ChatHeader = {
  [dmodel.RankType.LOW] = {
    'Low Rank Rewards:\n',
  },
  [dmodel.RankType.LOW] = {
    'High Rank Rewards:\n',
  },
  [dmodel.RankType.LOW] = {
    'Master Rank Rewards:\n',
  },
}

dmodel.DecorationsByRank = {
  [dmodel.RankType.LOW] = {
    { name = 'Carver Jewel', mh_index = 95 },
    { name = 'Hungerless Jewel', mh_index = 96 },
    { name = 'Furor Jewel', mh_index = 4 },
    { name = 'Blunt Jewel', mh_index = 28 },
    { name = 'Enhancer Jewel', mh_index = 31 },
    { name = 'Drain Jewel', mh_index = 42 },
    { name = 'Slider Jewel', mh_index = 43 },
    { name = 'Sonorous Jewel', mh_index = 44 },
    { name = 'Medicine Jewel', mh_index = 58 },
    { name = 'Recovery Jewel', mh_index = 59 },
    { name = 'Gobbler Jewel', mh_index = 60 },
    { name = 'Wind Res Jewel', mh_index = 62 },
    { name = 'Footing Jewel', mh_index = 63 },
    { name = 'Bubble Jewel', mh_index = 64 },
    { name = 'Fire Res Jewel', mh_index = 67 },
    { name = 'Water Res Jewel', mh_index = 68 },
    { name = 'Ice Res Jewel', mh_index = 69 },
    { name = 'Thunder Res Jewel', mh_index = 70 },
    { name = 'Dragon Res Jewel', mh_index = 71 },
    { name = 'Resistor Jewel', mh_index = 72 },
    { name = 'Botany Jewel', mh_index = 79 },
    { name = 'Geology Jewel', mh_index = 80 },
    { name = 'Grinder Jewel', mh_index = 85 },
    { name = 'Fungiform Jewel', mh_index = 87 },
    { name = 'Friendship Jewel', mh_index = 89 },
    { name = 'Brace Jewel', mh_index = 93 },
    { name = 'Satiated Jewel', mh_index = 90 },
    { name = 'Diversion Jewel', mh_index = 98 },
    { name = 'Rodeo Jewel', mh_index = 99 },
    { name = 'Wall Run Jewel', mh_index = 105 },
    { name = 'Counter Jewel', mh_index = 106 },
  },

  [dmodel.RankType.HIGH] = {
    { name = 'Blaze Jewel+', mh_index = 125 },
    { name = 'Stream Jewel+', mh_index = 128 },
    { name = 'Hard Stream Jewel+', mh_index = 130 },
    { name = 'Frost Jewel+', mh_index = 131 },
    { name = 'Bolt Jewel+', mh_index = 134 },
    { name = 'Dragon Jewel+', mh_index = 137 },
    { name = 'Defense Jewel+', mh_index = 140 },
    { name = 'Medicine Jewel+', mh_index = 145 },
    { name = 'Physique Jewel+', mh_index = 146 },
    { name = 'Bubble Jewel+', mh_index = 162 },
    { name = 'Gobbler Jewel+', mh_index = 152 },
    { name = 'Resistor Jewel+', mh_index = 153 },
    { name = 'Destryoer Jewel+', mh_index = 154 },
    { name = 'Quickswitch Jewel', mh_index = 107 },
    { name = 'Wirebug Jewel', mh_index = 104 },
    { name = 'Dive Jewel', mh_index = 97 },
    { name = 'Leap Jewel', mh_index = 94 },
    { name = 'Fortitude Jewel', mh_index = 92 },
    { name = 'Potential Jewel', mh_index = 91 },
    { name = 'Enduring Jewel', mh_index = 88 },
    { name = 'Artillery Jewel', mh_index = 45 },
    { name = 'Magazine Jewel', mh_index = 46 },
    { name = 'Ironwall Jewel', mh_index = 35 },
    { name = 'Refresh Jewel', mh_index = 34 },
    { name = 'Physique Jewel', mh_index = 33 },
    { name = 'Sprinter Jewel', mh_index = 32 },
    { name = 'Charger Jewel', mh_index = 30 },
    { name = 'Flawless Jewel', mh_index = 3 },
    { name = 'Mighty Jewel', mh_index = 10 },
    { name = 'Crit Element Jewel', mh_index = 11 },
    { name = 'Mastery Jewel', mh_index = 12 },
    { name = 'Blaze Jewel', mh_index = 13 },
    { name = 'Stream Jewel', mh_index = 14 },
    { name = 'Frost Jewel', mh_index = 15 },
    { name = 'Bolt Jewel', mh_index = 16 },
    { name = 'Dragon Jewel', mh_index = 17 },
    { name = 'Venom Jewel', mh_index = 18 },
    { name = 'Paralyzer Jewel', mh_index = 19 },
    { name = 'Sleep Jewel', mh_index = 20 },
    { name = 'Handicraft Jewel', mh_index = 22 },
    { name = 'Razor Jewel', mh_index = 23 },
    { name = 'Thrift Jewel', mh_index = 24 },
    { name = 'Sharp Jewel', mh_index = 25 },
    { name = "Mind's Eye Jewel", mh_index = 26 },
    { name = 'Precise Jewel', mh_index = 27 },
    { name = 'Gambit Jewel', mh_index = 39 },
    { name = 'Sheath Jewel', mh_index = 40 },
    { name = 'KO Jewel', mh_index = 41 },
    { name = 'Forceshot Jewel', mh_index = 48 },
    { name = 'Pierce Jewel', mh_index = 49 },
    { name = 'Spread Jewel', mh_index = 50 },
    { name = 'Capacity Jewel', mh_index = 51 },
    { name = 'Absorber Jewel', mh_index = 53 },
    { name = 'Sniper Jewel', mh_index = 54 },
    { name = 'Salvo Jewel', mh_index = 55 },
    { name = 'Defense Jewel', mh_index = 56 },
    { name = 'Guardian Jewel', mh_index = 37 },
    { name = 'Protection Jewel', mh_index = 57 },
    { name = 'Earplug Jewel', mh_index = 61 },
    { name = 'Evasion Jewel', mh_index = 65 },
    { name = 'Jumping Jewel', mh_index = 66 },
    { name = 'Antidote Jewel', mh_index = 73 },
    { name = 'Antipara Jewel', mh_index = 74 },
    { name = 'Pep Jewel', mh_index = 75 },
    { name = 'Steadfast Jewel', mh_index = 76 },
    { name = 'Muck Jewel', mh_index = 77 },
    { name = 'Antiblast Jewel', mh_index = 78 },
    { name = 'Destroyer Jewel', mh_index = 81 },
    { name = 'Bomber Jewel', mh_index = 86 },
  },

  [dmodel.RankType.MASTER] = {
    { name = 'Attack Jewel', mh_index = 1 },
    { name = 'Challenger Jewel', mh_index = 2 },
    { name = 'Crisis Jewel', mh_index = 5 },
    { name = 'Expert Jewel', mh_index = 6 },
    { name = 'Critical Jewel', mh_index = 7 },
    { name = 'Tenderizer Jewel', mh_index = 8 },
    { name = 'Throttle Jewel', mh_index = 9 },
    { name = 'Blast Jewel', mh_index = 21 },
    { name = 'Shield Jewel', mh_index = 36 },
    { name = 'Draw Jewel', mh_index = 38 },
    { name = 'Trueshot Jewel', mh_index = 47 },
    { name = 'Quickload Jewel', mh_index = 52 },
    { name = 'Fate Jewel', mh_index = 84 },
    { name = 'Hellfire Jewel', mh_index = 108 },
    { name = 'Hard Fire Res Jewel', mh_index = 110 },
    { name = 'Hard Water Res Jewel', mh_index = 111 },
    { name = 'Hard Ice Res Jewel', mh_index = 112 },
    { name = 'Hard Thunder Res Jewel', mh_index = 113 },
    { name = 'Hard Dragon Res Jewel', mh_index = 114 },
    { name = 'Hard Antidote Jewel', mh_index = 115 },
    { name = 'Hard Antipara Jewel', mh_index = 116 },
    { name = 'Hard Pep Jewel', mh_index = 117 },
    { name = 'Hard Antiblast Jewel', mh_index = 118 },
    { name = 'Hard Botany Jewel', mh_index = 119 },
    { name = 'Hard Geology Jewel', mh_index = 120 },
    { name = 'Hard Satiated Jewel', mh_index = 121 },
    { name = 'Hard Drain Jewel', mh_index = 122 },
    { name = 'Hard Enduring Jewel', mh_index = 123 },
    { name = 'Hard Hungerless Jewel', mh_index = 124 },
    { name = 'Hard Blaze Jewel', mh_index = 126 },
    { name = 'Hard Blaze Jewel+', mh_index = 127 },
    { name = 'Hard Stream Jewel', mh_index = 129 },
    { name = 'Hard Frost Jewel', mh_index = 132 },
    { name = 'Hard Frost Jewel+', mh_index = 133 },
    { name = 'Hard Bolt Jewel', mh_index = 135 },
    { name = 'Hard Bolt Jewel+', mh_index = 136 },
    { name = 'Hard Dragon Jewel', mh_index = 138 },
    { name = 'Hard Dragin Jewel+', mh_index = 139 },
    { name = 'Hard Defense Jewel', mh_index = 141 },
    { name = 'Hard Defense Jewel++', mh_index = 142 },
    { name = 'Hard Bomber Jewel', mh_index = 143 },
    { name = 'Hard Grinder Jewel', mh_index = 144 },
    { name = 'Hard Wall Run Jewel', mh_index = 148 },
    { name = 'Wirebug Jewel+', mh_index = 147 },
    { name = 'Hard Venom Jewel', mh_index = 149 },
    { name = 'Hard Recovery Jewel', mh_index = 150 },
    { name = 'Protection Jewel+', mh_index = 151 },
    { name = 'Hard Friendship Jewel', mh_index = 155 },
    { name = 'Hard Friendship Jewel+', mh_index = 156 },
    { name = 'Evasion Jewel+', mh_index = 157 },
    { name = 'Sheath Jewel+', mh_index = 158 },
    { name = 'Hard Sniper Jewel', mh_index = 159 },
    { name = 'Gambit Jewel+', mh_index = 160 },
    { name = 'Hard Brace Jewel', mh_index = 161 },
    { name = 'KO Jewel+', mh_index = 163 },
    { name = 'Jumping Jewel+', mh_index = 164 },
    { name = 'Hard Wind Res Jewel', mh_index = 165 },
    { name = 'Counter Jewel+', mh_index = 166 },
    { name = 'Refresh Jewel+', mh_index = 169 },
    { name = 'Ironwall Jewel+', mh_index = 170 },
    { name = 'Shield Jewel+', mh_index = 171 },
    { name = 'Precise Jewel+', mh_index = 172 },
    { name = 'Mighty Jewel+', mh_index = 173 },
    { name = 'Crit Element Jewel+', mh_index = 174 },
    { name = 'Charger Jewel+', mh_index = 175 },
    { name = 'Sprinter Jewel+', mh_index = 176 },
    { name = 'Guardian Jewel+', mh_index = 177 },
    { name = 'Draw Jewel+', mh_index = 179 },
    { name = 'Fungiform Jewel+', mh_index = 180 },
    { name = 'Hard Steadfast Jewel', mh_index = 181 },
    { name = 'Potential Jewel+', mh_index = 182 },
    { name = 'Razor Jewel+', mh_index = 183 },
    { name = "Mind's Eye Jewel+", mh_index = 185 },
    { name = 'Quickswitch Jewel+', mh_index = 186 },
    { name = 'Artillery Jewel+', mh_index = 187 },
    { name = 'Earplug Jewel+', mh_index = 188 },
    { name = 'Enhancer Jewel+', mh_index = 189 },
    { name = 'Trueshot Jewel+', mh_index = 190 },
    { name = 'Magazine Jewel+', mh_index = 191 },
    { name = 'Footing Jewel+', mh_index = 192 },
    { name = 'Blast Jewel+', mh_index = 193 },
    { name = 'Spread Jewel+', mh_index = 194 },
    { name = 'Furor Jewel+', mh_index = 196 },
    { name = 'Furor Jewel+', mh_index = 197 },
    { name = 'Throttle Jewel+', mh_index = 198 },
    { name = 'Paralyzer Jewel+', mh_index = 199 },
    { name = 'Sleep Jewel+', mh_index = 200 },
    { name = 'Sharp Jewel+', mh_index = 201 },
    { name = 'Forceshot Jewel+', mh_index = 202 },
    { name = 'Pierce Jewel+', mh_index = 203 },
    { name = 'Hellfire Jewel+', mh_index = 205 },
    { name = 'Handicraft Jewel+', mh_index = 206 },
    { name = 'Fate Jewel+', mh_index = 207 },
    { name = 'Mastery Jewel+', mh_index = 208 },
    { name = 'Flawless Jewel+', mh_index = 209 },
    { name = 'Foil Jewel', mh_index = 210 },
    { name = 'Polisher Pro Jewel', mh_index = 211 },
    { name = 'SpiritBird´s Call jewel', mh_index = 212 },
    { name = 'Charge Jewel', mh_index = 213 },
    { name = 'Phoenix Jewel', mh_index = 214 },
    { name = 'Bladescale Jewel', mh_index = 215 },
    { name = 'Flywall Jewel', mh_index = 216 },
    { name = 'Chain Jewel', mh_index = 217 },
    { name = 'Redirection Jewel', mh_index = 218 },
    { name = 'Foray Jewel', mh_index = 219 },
    { name = 'Breath Jewel', mh_index = 221 },
    { name = 'Mighty Bow Jewel', mh_index = 223 },
    { name = 'Sniper Jewel+', mh_index = 224 },
    { name = 'Cornerstone Jewel', mh_index = 225 },
    { name = 'Elemental Exploit Jewel', mh_index = 226 },
    { name = 'Counter Attack Jewel', mh_index = 227 },
    { name = 'Backstab Jewel', mh_index = 228 },
    { name = 'Trigger Jewel', mh_index = 230 },
    { name = 'Embolden Jewel', mh_index = 231 },
    { name = 'Intrepid Jewel', mh_index = 232 },
    { name = 'Phoenix Jewel+', mh_index = 238 },
    { name = 'Haze Jewel', mh_index = 239 },
    { name = 'Charge Jewel+', mh_index = 240 },
    { name = 'Foil Jewel+ ', mh_index = 241 },
    { name = 'Bloodening Jewel', mh_index = 242 },
    { name = 'Polisher Pro Jewel+', mh_index = 243 },
    { name = 'Ironshell Jewel', mh_index = 244 },
    { name = 'Flamescale Jewel', mh_index = 245 },
    { name = 'Rediraction Jewel+', mh_index = 246 },
    { name = 'Dragon Spirit Jewel', mh_index = 247 },
    { name = 'Element Exploit Jewel+', mh_index = 248 },
    { name = 'Hard Cornerstone Jewel', mh_index = 249 },
    { name = 'Counter Attack Jewel+', mh_index = 250 },
    { name = 'Backstab Jewel+', mh_index = 251 },
    { name = 'Foray Jewel+', mh_index = 252 },
    { name = 'Chain Jewel+', mh_index = 253 },
    { name = 'Bloddlust Jewel', mh_index = 254 },
    { name = 'Eembolden Jewel+', mh_index = 255 },
    { name = 'Intrepid Jewel+', mh_index = 256 },
    { name = 'Trigger Jewel+', mh_index = 257 },
    { name = 'Shockproof Jewel', mh_index = 259 },
    { name = 'Bladescale Jewel+', mh_index = 261 },
  },
}

dmodel.RampageDecorationsByRank = {
  [dmodel.RankType.LOW] = {
    { name = 'Doot Range Jewel', mh_index = 6 },
    { name = 'Small Monster Jewel', mh_index = 13 },
    { name = 'Rally Jewel', mh_index = 25 },
    { name = 'Spiritbird Jewel', mh_index = 26 },
  },
  [dmodel.RankType.HIGH] = {
    { name = 'Brutal Jewel', mh_index = 1 },
    { name = 'Defense Edge Jewel', mh_index = 3 },
    { name = 'Anti-Wyvern Jewel', mh_index = 10 },
    { name = 'Anti-Aerial Jewel', mh_index = 11 },
    { name = 'Anti-Aquatic Jewel', mh_index = 12 },
    { name = 'Fireblight Jewel', mh_index = 14 },
    { name = 'Waterblight Jewel', mh_index = 15 },
    { name = 'Thunderblight Jewel', mh_index = 16 },
    { name = 'Iceblight Jewel', mh_index = 17 },
    { name = 'Fanged Exploit Jewel', mh_index = 28 },
    { name = 'Bloody Jewel', mh_index = 29 },
    { name = 'Wirebug Jewel', mh_index = 30 },
    { name = 'Growth Jewel', mh_index = 31 },
  },
  [dmodel.RankType.MASTER] = {
    { name = 'Wyrmstake Jewel', mh_index = 27 },
    { name = 'Defense Master Jewel', mh_index = 4 },
    { name = 'Switcher Jewel', mh_index = 7 },
    { name = 'Arc Jewel', mh_index = 8 },
    { name = 'Teostra Soul Jewel', mh_index = 9 },
    { name = 'Magna Soul Jewel', mh_index = 18 },
    { name = 'Valstrax Soul Jewel', mh_index = 19 },
    { name = 'Chameleos Soul Jewel', mh_index = 20 },
    { name = 'Daora Soul Jewel', mh_index = 21 },
    { name = 'Ibushi Soul Jewel', mh_index = 23 },
    { name = 'Narwa Soul Jewel', mh_index = 24 },
    { name = 'Stun Jewel', mh_index = 32 },
    { name = 'Demon Rage Jewel', mh_index = 33 },
    { name = 'Supercharge Jewel', mh_index = 34 },
    { name = 'Guardbash Jewel', mh_index = 35 },
    { name = 'Brutal Jewel', mh_index = 1 },
    { name = 'Defense Edge Jewel', mh_index = 3 },
    { name = 'Anti-Wyvern Jewel', mh_index = 10 },
    { name = 'Anti-Aerial Jewel', mh_index = 11 },
    { name = 'Anti-Aquatic Jewel', mh_index = 12 },
    { name = 'Fireblight Jewel', mh_index = 14 },
    { name = 'Waterblight Jewel', mh_index = 15 },
    { name = 'Thunderblight Jewel', mh_index = 16 },
    { name = 'Iceblight Jewel', mh_index = 17 },
    { name = 'Fanged Exploit Jewel', mh_index = 28 },
    { name = 'Bloody Jewel', mh_index = 29 },
    { name = 'Wirebug Jewel', mh_index = 30 },
    { name = 'Growth Jewel', mh_index = 31 },
    { name = 'Doot Range Jewel', mh_index = 6 },
    { name = 'Small Monster Jewel', mh_index = 13 },
    { name = 'Rally Jewel', mh_index = 25 },
    { name = 'Spiritbird Jewel', mh_index = 26 },
  },
}

dmodel.UnluckyRampageDecorations = {
  [22] = 'Unlucky',
}

dmodel.RampageDecorations = {
  [1] = 'Brutal Jewel',
  [2] = 'Elembane Jewel',
  [3] = 'Defense Edge Jewel',
  [4] = 'Defense Master Jewel',
  [5] = 'Raging Jewel',
  [6] = 'Doot Range Jewel',
  [7] = 'Switcher Jewel',
  [8] = 'Arc Jewel',
  [9] = 'Teostra Soul Jewel',
  [10] = 'Anti-Wyvern Jewel',
  [11] = 'Anti-Aerial Jewel',
  [12] = 'Anti-Aquatic Jewel',
  [13] = 'Small Monster Jewel',
  [14] = 'Fireblight Jewel',
  [15] = 'Waterblight Jewel',
  [16] = 'Thunderblight Jewel',
  [17] = 'Iceblight Jewel',
  [18] = 'Magna Soul Jewel',
  [19] = 'Valstrax Soul Jewel',
  [20] = 'Chameleos Soul Jewel',
  [21] = 'Daora Soul Jewel',
  [23] = 'Ibushi Soul Jewel',
  [24] = 'Narwa Soul Jewel',
  [25] = 'Rally Jewel',
  [26] = 'Spiritbird Jewel',
  [27] = 'Wyrmstake Jewel',
  [28] = 'Fanged Exploit Jewel',
  [29] = 'Bloody Jewel',
  [30] = 'Wirebug Jewel',
  [31] = 'Growth Jewel',
  [32] = 'Stun Jewel',
  [33] = 'Demon Rage Jewel',
  [34] = 'Supercharge Jewel',
  [35] = 'Guardbash Jewel',
}

---@enum DecorationCategory
dmodel.DecorationCategory = {
  RAMPAGE = 'RAMPAGE',
  NORMAL = 'NORMAL',
}

dmodel.DecorationTableByRank = {
  [dmodel.DecorationCategory.NORMAL] = dmodel.DecorationsByRank,
  [dmodel.DecorationCategory.RAMPAGE] = dmodel.RampageDecorationsByRank,
}

---@enum DecorationGamblingCategory
dmodel.DecorationGamblingCategory = {
  [dmodel.DecorationCategory.NORMAL] = 0,
  [dmodel.DecorationCategory.RAMPAGE] = 1,
}

dmodel.RankTypeToDecorationCategoryOdds = {
  [dmodel.RankType.LOW] = {
    [dmodel.DecorationCategory.NORMAL] = {
      min = 1,
      max = 6,
      chance = 50,
    },
    [dmodel.DecorationCategory.RAMPAGE] = {
      min = 0,
      max = 1,
      chance = 5,
    },
  },
  [dmodel.RankType.HIGH] = {
    [dmodel.DecorationCategory.NORMAL] = {
      min = 2,
      max = 7,
      chance = 50,
    },
    [dmodel.DecorationCategory.RAMPAGE] = {
      min = 0,
      max = 1,
      chance = 5,
    },
  },
  [dmodel.RankType.MASTER] = {
    [dmodel.DecorationCategory.NORMAL] = {
      min = 3,
      max = 8,
      chance = 30,
    },
    [dmodel.DecorationCategory.RAMPAGE] = {
      min = 0,
      max = 2,
      chance = 5,
    },
  },
}

return dmodel
